apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomerce-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomerce-app
      version: blue
  template:
    metadata:
      labels:
        app: ecomerce-app
        version: blue
    spec:
      containers:
      - name: ecomerce-app
        image: waseem09/ecomerce-site:30
        ports:
        - containerPort: 3000
