apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomerce-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomerce-app
      version: green
  template:
    metadata:
      labels:
        app: ecomerce-app
        version: green
    spec:
      containers:
      - name: ecomerce-app
        image: waseem09/ecomerce-site:31   # new version
        ports:
        - containerPort: 3000
