apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomerce-deployment  
  labels:
    app: ecomerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomerce-app
  template:
    metadata:
      labels:
        app: ecomerce-app
    spec:
      containers:
      - name: ecomerce-app
        image: waseem09/ecomerce-site:18
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi" 
            cpu: "100m"
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ecomerce-service
  labels:
    app: ecomerce-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30008 
  selector:
    app: ecomerce-app
