apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomerce-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomerce-app
      version: blue
  template:
    metadata:
      labels:
        app: ecomerce-app
        version: blue
    spec:
      containers:
      - name: ecomerce-app
        image: waseem09/ecomerce-site:30
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomerce-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomerce-app
      version: green
  template:
    metadata:
      labels:
        app: ecomerce-app
        version: green
    spec:
      containers:
      - name: ecomerce-app
        image: waseem09/ecomerce-site:31
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ecomerce-service
  labels:
    app: ecomerce-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30008 
  selector:
    app: ecomerce-app
    version: green
